version: "3.8"
services:
  redis:
    image: redis:7
    container_name: redis_ai_seo_gsheet

  celery:
    container_name: celery_chatgpt
    build:
      context: .
    working_dir: /app
    command: ["celery", "-A", "celery_app", "worker", "--loglevel=INFO", "--pool=gevent"]
    depends_on:
      - redis

  ai_seo_gsheet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_seo_gsheet
    command: ["python", "-u", "./app/main.py"]
    depends_on:
      - celery