version: "3.8"
services:
  redis:
    image: redis:7
    container_name: redis_ai_seo_gsheet
    networks:
      - AI_SEO

  celery:
    container_name: celery_chatgpt
    build:
      context: .
    command: ["celery", "-A", "app.queue", "worker", "--loglevel=INFO", "--pool=prefork", "--concurrency=3"]
    depends_on:
      - redis
    networks:
      - AI_SEO

  ai_seo_gsheet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_seo_gsheet
    command: ["python", "-m", "app.main"]
    depends_on:
      - celery
    networks:
      - AI_SEO
networks:
  AI_SEO:
    external: True
    name: "AI_SEO"